apiVersion: v1
kind: ConfigMap
metadata:
  name: cicdapp-configmap
  namespace: mynamespace
data:
  #MONGO_URI: "mongodb://cicdapp_mongo:27017/mydatabase"
  MONGO_URI: "mongodb://mongodb-0.mongodb.mynamespace.svc.cluster.local:27017,mongodb-1.mongodb.mynamespace.svc.cluster.local:27017,mongodb-2.mongodb.mynamespace.svc.cluster.local:27017/mydatabase?replicaSet=rs0"

