# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    container_name: cicdapp
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
      #- MONGO_URI=mongodb://alex24:alextheroot24@mongo:27017/mydatabase
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:5.0
    container_name: cicdapp_mongo
    restart: always
   # environment:
     # MONGO_INITDB_ROOT_USERNAME: alex24
     # MONGO_INITDB_ROOT_PASSWORD: alextheroot24
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
